== TicketManor

This is a demo application of building enterprise applications using Java EE. There are expected to be
a variety of APIs used, e.g., Java EE (JPA, EJB), Spring Framework, modern SPA Web (Angular, Ember.JS),
and so on.

It will be used as a showcase in various courses offered by http://learningtree.com/[Learning Tree],
the world leader in instructor-led tecnical training. Learning Tree offers courses in Java
as well as many other enterprise applications.

Legal Note: We do _not_ intend this to be a passing-off of TicketMaster.com, which is a trademark in
most countries. It is just a demonstration of how certain parts of an enterprise app could
be implemented. WE ARE NOT ACTUALLY SELLING ANY TICKETS.

This site is *not* affiliated in any way with http://ticketmaster.com/[TicketMaster(TM)] nor any
other commercial ticket selling organization.

=== Deployment

This is configured to deploy with the EE Server WildFly 8+

You MUST change the file ${WILDFLYHOME}/standalone/configuration/standalone.sh to have
a datasource named TicketManorDataSource.  For initial testing I just added:

	<datasource jndi-name="java:jboss/datasources/TicketManorDataSource" pool-name="TicketManorPool" 
		enabled="true" use-java-context="true">
		<connection-url>jdbc:h2:mem:ticketmanor;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE</connection-url>
		<driver>h2</driver>
		<security>
			<user-name>sa</user-name>
			<password>sa</password>
		</security>
	</datasource>

We will need to change this to MySQL or a real database before deployment.
